export const FLUSH_DB_DATA = "FLUSH_DB_DATA";
export const FLUSH_DB_SUCCESS = "FLUSH_DB_SUCCESS";
export const FLUSH_DB_FAILURE = "FLUSH_DB_FAILURE";

export const CONTAINER_RESTART_DATA = 'CONTAINER_RESTART_DATA';
export const CONTAINER_RESTART_SUCCESS = 'CONTAINER_RESTART_SUCCESS';
export const CONTAINER_RESTART_FAILURE = 'CONTAINER_RESTART_FAILURE';

export const NEO4J_STATUS_DATA = "NEO4J_STATUS_DATA";
export const NEO4J_STATUS_SUCCESS = "NEO4J_STATUS_SUCCESS";
export const NEO4J_STATUS_FAILURE = "NEO4J_STATUS_FAILURE";

export const RELOAD_DATA = "RELOAD_DATA";
export const RELOAD_SUCCESS = "RELOAD_SUCCESS";
export const RELOAD_FAILURE = "RELOAD_FAILURE";

export const STORAGE_CHANGE = "STORAGE_CHANGE";
export const STORAGE_CHANGE_SUCCESS = "STORAGE_CHANGE_SUCCESS";
export const STORAGE_CHANGE_FAILURE = "STORAGE_CHANGE_FAILURE";

export const USER_LIST_DATA = "USER_LISTL_DATA";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAILURE = "USER_LIST_FAILURE";

export const USER_PENDING_DATA = "USER_PENDING_DATA";
export const USER_PENDING_SUCCESS = "USER_PENDING_SUCCESS";
export const USER_PENDING_FAILURE = "USER_PENDING_FAILURE";

export const USER_APPROVE_DATA = "USER_APPROVE_DATA";
export const USER_APPROVE_SUCCESS = "USER_APPROVE_SUCCESS";
export const USER_APPROVE_FAILURE = "USER_APPROVE_FAILURE";

export const USER_DELETE_DATA = "USER_DELETE_DATA";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE";

export const USER_REJECT_DATA = "USER_REJECT_DATA";
export const USER_REJECT_SUCCESS = "USER_REJECT_SUCCESS";
export const USER_REJECT_FAILURE = "USER_REJECT_FAILURE";

export const USER_ROLE_EDIT_DATA = "USER_REJECT_DATA";
export const USER_ROLE_EDIT_SUCCESS = "USER_REJECT_SUCCESS";
export const USER_ROLE_EDIT_FAILURE = "USER_REJECT_FAILURE";

export const USER_RESET_PASSWORD_DATA = "USER_RESET_PASSWORD_DATA";
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_FAILURE = "USER_RESET_PASSWORD_FAILURE";