export const UPLOAD_CHAT_DOCUMENT_DATA = "UPLOAD_CHAT_DOCUMENT_DATA";
export const UPLOAD_CHAT_DOCUMENT_SUCCESS = "UPLOAD_CHAT_DOCUMENT_SUCCESS";
export const UPLOAD_CHAT_DOCUMENT_FAILURE = "UPLOAD_CHAT_DOCUMENT_FAILURE";
export const UPLOAD_LINK_DOCUMENT_DATA ='UPLOAD_LINK_DOCUMENT';
export const UPLOAD_LINK_DOCUMENT_SUCCESS ='UPLOAD_LINK_DOCUMENT';
export const UPLOAD_LINK_DOCUMENT_FAILURE ='UPLOAD_LINK_DOCUMENT';


