export const PARTITION_LIST_DATA ='PARTITION_LIST_DATA'
export const PARTITION_LIST_SUCCESS ='PARTITION_LIST_SUCCESS'
export const PARTITION_LIST_FAILURE = 'PARTITION_LIST_FAILURE'

export const PARTITION_META_DATA ='PARTITION_META_DATA'
export const PARTITION_META_SUCCESS ='PARTITION_META_SUCCESS'
export const PARTITION_META_FAILURE = 'PARTITION_META_FAILURE'