export const START_CHAT_SESSION = 'START_CHAT_SESSION';
export const END_CHAT_SESSION = 'END_CHAT_SESSION';
export const UPDATE_CHAT_SESSION = 'UPDATE_CHAT_SESSION';
export const CHAT_SESSION_ERROR = 'CHAT_SESSION_ERROR';